version: 2
project_name: kt-connect

before:
  hooks:
    - make mod

builds:
  - id: ktctl
    main: ./cmd/ktctl/main.go
    binary: ktctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    # 使用简洁的标准命名，避免复杂的替换导致冲突
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: gitlayzer
    name: kt-connect
  draft: false
  prerelease: auto
